services:
  api:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      REDIS_HOST: redis
      DB_HOST: db
    env_file:
      - .env
    depends_on:
      - db

  redis:
    image: redis:latest
    container_name: academy_wallet_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: ['redis-server', '--appendonly', 'yes']

  db:
    image: postgres:latest
    container_name: academy_wallet
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: db_wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
    driver: local
  postgres_data:
